# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [57]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [58]:
A = np.arange(1, 16).reshape(3,5)
print (A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [59]:
print("Dimension (number of axes):", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Datatype:", A.dtype)

Dimension (number of axes): 2
Shape: (3, 5)
Size: 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [60]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print ()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [61]:
elementwise_subtraction = B - C
elementwise_multiplication = B * C
matrix_multiplication = B @ C

print (elementwise_subtraction)
print (elementwise_multiplication)
print (matrix_multiplication)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [62]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
elementwise_exponentiated = np.exp(B)
print (elementwise_exponentiated)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [64]:
matrix_minimum = B.min ()
row_minimum = B.min(axis=1)
colum_minimum = B.min(axis=0)
matrix_index_minimum = np.argmin(B)
row_index_minimum = np.argmin(B, axis=1)
elements_sum = B.sum ()
colum_mean = B.mean (axis=0)
colum_median = np.median (B, axis=0)

In [65]:
print (matrix_minimum)
print (row_minimum)
print (colum_minimum)
print (matrix_index_minimum)
print (row_index_minimum)
print (row_minimum)
print (elements_sum)
print (colum_mean)
print (colum_median)

1
[1 4 7]
[1 2 3]
0
[0 0 0]
[1 4 7]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [66]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [67]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [69]:
# Matrisen A har två axlar. Axel 0 som är rader och axel 1 som är kolumner.
# I axel 0 (rad) finns det 3 rader med index 0,1 och 2.
# I axel 1 (kolum) finns det 5 kolumner med index 0,1, 2, 3 och 4. 

# För A[1] anges bara index 1, kommer python förstå att man vill indexera längs axel 0 (rader).
# Detta betyder att alla kolumner i rad 1 ska tas med, vilket i detta fall är 6,7,8,9 och 10.

# Detta exempel visar att när man anger färre index än antalet axlar i en Numpy matrisen, kommer
# Python förstår automatiskt att man viill ta med hela innehåller i de axlar man inte angiviit något index för. 

# Vill man ha innehållet längst axal 0 (rad) anger man index för kolumn som man vill ha.
A[:, 2]

array([ 3,  8, 13])

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [70]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [71]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [74]:
for i in np.nditer (A):
    print (i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [14]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# a = np.arrange (30) betyder att det skapar en endimensionell array som innehåller heltal från 0 tll 29.

# b ska ändra formen på array a från endiimensionell till tre dimensinell med formen 2, 3 och -1. 

# b har tre demensioner, vilket betyder att det har tre axlar:
# Axel 0:  Representerar de två lagren (eller "blocken") med data, så den har storleken 2.
# Axel 1: Representerar de tre raderna i varje block, så den har storleken 3.
# Axel 2: Representerar de fem värdena i varje rad, så den har storleken 5.


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [15]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [16]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [17]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [49]:
def add_mult_matrices(matrix1, matrix2, operation):
    
    # Validate that inputs are numpy arrays
    if not (isinstance(matrix1, np.ndarray) and isinstance(matrix2, np.ndarray)):
        raise TypeError("Both inputs must be of type numpy.ndarray")

    # Validate the operation
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation must be either 'add' or 'multiply'")

    # Perform addition
    if operation == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same dimensions for addition")
        return matrix1 + matrix2

    # Perform multiplication
    if operation == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Number of columns in the first matrix must equal the number of rows in the second matrix for multiplication")
        return np.dot(matrix1, matrix2)

# Example usage:
if __name__ == "__main__":
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

    # Addition
    try:
        result_add = add_mult_matrices(A, B, 'add')
        print("Addition Result:")
        print(result_add)
    except Exception as e:
        print(f"Addition Error: {e}")

    # Multiplication
    try:
        result_mult = add_mult_matrices(A, B, 'multiply')
        print("Multiplication Result:")
        print(result_mult)
    except Exception as e:
        print(f"Multiplication Error: {e}")


Addition Result:
[[ 6  8]
 [10 12]]
Multiplication Result:
[[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

#### Uppgift 10.1.1 Definiera vektorn x enligt nedan   
    x = (4, 3)


In [22]:
y = np.array([4, 3])
x = y.reshape (1, 2)


#(a) Vilken dimension har vektorn x?
print ("a:", x.shape)
# Vektorn x = (4, 3) har demesionen 1 x 2.

# (b) Beräkna 5x.
Beräkna_5x = 5 * x

# (c) Beräkna 3x.
Beräkna_3x = 3 * x

# (d) Beräkna 5x + 3x.
Beräkna_5x_plus_3x = Beräkna_5x + Beräkna_3x

# (e) Beräkna 8x.
Beräkna_8x = 8 * x

# (f) Beräkna 4x − x.
Beräkna_4x_minus_x = 4 * x - x

# (g) Beräkna x⊤, vilken blir den nya dimensionen efter att transponeringen utförat?
xT = y.reshape (2, 1)
# och den nya dimensionen efter transponeringen är  2 × 1.

#(h) Är x + x⊤ definierat?
# Det är inte defiinerat eftersom x har dimesionen 1 x 2 och xT har dimensionen 2 x 1. 

#(i) Beräkna ∥x∥.
Beräkna_x_norm = np.linalg.norm(x)

print ("b:", Beräkna_5x)
print ("c:", Beräkna_3x)
print ("d:", Beräkna_5x_plus_3x)
print ("e:", Beräkna_8x)
print ("f:", Beräkna_4x_minus_x)
print ("g:", xT)
print ("i:", Beräkna_x_norm)

a: (1, 2)
b: [[20 15]]
c: [[12  9]]
d: [[32 24]]
e: [[32 24]]
f: [[12  9]]
g: [[4]
 [3]]
i: 5.0


#### Uppgift 10.1.2. Definiera vektorn v enligt nedan.
vT = (3,7,0,11)

In [23]:
x = np.array([3, 7, 0, 11])
v = x.reshape (4,1)

# (a) Vilken dimension har vektorn v?
v.shape
# Vektorn v har dimesonen 4 x 1. Vilket betyder att 4 rader och en kolum

# (b) Beräkna 2v.
Beräkna_2v = 2 * v

# (c)Beräkna 5v + 2v
Beräkna_5v_plus_2v = 5 * v + Beräkna_2v

# (d) Beräkna 4v − 2v.
Beräkna_4v_minus_2v = 4 * v - Beräkna_2v

# (e) Beräkna v⊤, vilken blir den nya dimensionen efter att transponeringen utförts?
vT = x.reshape (1,4)
# vT har dimensionen 1 x 4 efter transponeneringen

# (f) Beräkna ∥v∥.
Beräkna_v_norm = np.linalg.norm (v)


print ("a:", v.shape)
print ("b:", Beräkna_2v)
print ("c:", Beräkna_5v_plus_2v)
print ("d:", Beräkna_4v_minus_2v)
print ("e:", vT)
print ("f:", Beräkna_v_norm)

a: (4, 1)
b: [[ 6]
 [14]
 [ 0]
 [22]]
c: [[21]
 [49]
 [ 0]
 [77]]
d: [[ 6]
 [14]
 [ 0]
 [22]]
e: [[ 3  7  0 11]]
f: 13.379088160259652


#### Uppgift 10.1.3. Definiera vektorerna 
v1 = (4, 3, 1, 5) och
v2 = (2, 3, 1, 1).

In [24]:
x = np.array ([4,3,1,5])
v1 = x.reshape (1,4)

y = np.array ([2,3,1,1])
v2 = y.reshape (1,4)


#(a) Beräkna ∥v1∥.
Beräkna_v1_norm = np.linalg.norm(v1)

# (b) Beräkna ∥v1 - v2∥
Beräkna_v1_minus_v2_norm = np.linalg.norm(v1-v2)

print ("a:", Beräkna_v1_norm)
print ("b:", Beräkna_v1_minus_v2_norm)

a: 7.14142842854285
b: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

#### Uppgift 10.2.4
##### Skriv det linjära ekvationssystemet nedan på formen Ax = b.
##### 3x1 + 2x2 + 4x3 = 7
##### 2x1 + 3x2 + 8x3 = 4
##### 4x1 + x2 + 3x3 = 11
##### 7x1 + x2 + 5x3 = 9

In [47]:
A = np.array ([
    [3, 2, 4],
    [2, 3, 8],
    [4, 1, 3],
    [7, 1, 5]
])

print (A)
a = np.array([7, 4, 11, 9])
b = a.reshape (4,1)
print (b)


x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)
Ax = A @ x


[[3 2 4]
 [2 3 8]
 [4 1 3]
 [7 1 5]]
[[ 7]
 [ 4]
 [11]
 [ 9]]
Solution vector x (least squares):
[[ 2.13691417]
 [ 4.83412322]
 [-1.89152185]]
Ax =
[[ 8.51290153]
 [ 3.64402317]
 [ 7.70721432]
 [10.33491311]]
Is Ax close to b?  False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [18]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [19]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [20]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
